name: Build and deploy Node.js app to Azure Web App - tech0-gen-11-step3-2-node-55

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: Prepare standalone artifact
        run: |
          mkdir -p ./deploy_package
          
          # フォルダの中身ではなく、フォルダ自体をターゲットにしてコピー
          cp -r .next/standalone ./deploy_package/
          
          # 静的ファイルとpublicをコピー（パスを調整）
          mkdir -p ./deploy_package/standalone/.next/static
          cp -r .next/static/. ./deploy_package/standalone/.next/static/
          cp -r public ./deploy_package/standalone/public

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app  # ここがdeployジョブの名前と一致している必要があります
          path: ./deploy_package # 作成したフォルダを指定

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./release # 明示的な展開先を指定

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tech0-gen-11-step3-2-node-55'
          package: ./release/standalone # standaloneフォルダの中身をデプロイ
          clean: true
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DA2DC9F9F5AD4D79A7470E2982B67D92 }}